FROM apache/airflow:2.11.0

USER airflow

RUN  pip install --no-cache-dir \
      apache-airflow-providers-amazon \
      apache-airflow-providers-trino \
      boto3 \
      minio \
      soda-core-trino

USER airflow
